export const drugs = {
    ADRENALIN: { name: 'Adrenalin', conc: [.01], unit: 'mg/ml', formula: [1], class: 'vaso', dialogText: 'Adrenalin dialog text' },
    ADRENALIN_STANS: { name: 'Adrenalin', conc: [.1], unit: 'mg/ml', formula: [10], max: [1000], class: 'vaso', dialogText: 'test' },
    AMIODARON1: { name: 'Amiodaron', conc: [50], unit: 'mg/ml', formula: [5000], max: [300000], dialogText: 'Cordarone' },
    AMIODARON2: { name: 'Amiodaron', conc: [50], unit: 'mg/ml', formula: [5000], max: [150000], dialogText: 'Cordarone' },
    ALFENTANIL: { name: 'Alfentanil', conc: [.5], unit: 'mg/ml', formula: [5, 30], class: 'opioid', dialogText: 'test<h3>test</h3>' },
    ATROPIN: { name: 'Atropin', conc: [1], unit: 'mg/ml', formula: [10, 20], max: [1000], class: 'antimuscarinic', dialogText: 'test' },
    BENPEN: { name: 'Benpen', conc: [10], unit: 'mg/ml', formula: [25000], max: [1200000], dialogText: 'test' },
    BUPIVACAIN: { name: 'Bupivakain', conc: [2.5], unit: 'mg/ml', formula: [2500], class: 'local', dialogText: 'Marcain' },
    CALCIUMGLUKONAT: { name: 'Calciumglukonat', conc: [.225], unit: 'mmol/ml', formula: [100], max: [4500], dialogText: 'test' },
    CEFAZOLIN: { name: 'Cefazolin', conc: [100], unit: 'mg/ml', formula: [30000], max: [2000000], dialogText: 'test' },
    CEFUROXIM: { name: 'Cefuroxim', conc: [100], unit: 'mg/ml', formula: [50000], max: [1500000], dialogText: 'test' },
    CISATRACURIUM: { name: 'Cisatrakurium', conc: [2], unit: 'mg/ml', formula: [150], max: [100000], class: 'nmbd', dialogText: 'Nimbex' },
    DEKSAMETASON: { name: 'Deksametason', conc: [4], unit: 'mg/ml', formula: [100, 400], max: [12000], dec: [1], dialogText: 'Dexavit brukes til barn under skolealder' },
    DEKSMEDETOMIDIN_N: { name: 'Deksmedetomidin (nasal)*', conc: [.1], unit: 'mg/ml', formula: [2, 4], max: [200], dv: [.1], dialogText: 'Dexdor, * Doseringsvolum for nasal administrasjon er oppgitt inkludert dødvolum på 0,1 ml' },
    DIAZEPAM: { name: 'Diazepam', conc: [5], unit: 'mg/ml', formula: [100], class: 'benzo', dialogText: 'test' },
    FENTANYL: { name: 'Fentanyl', conc: [.05], unit: 'mg/ml', formula: [1, 3], max: [200], class: 'opioid', dialogText: 'Her kommer det endel nyttig tekst om legemiddelet<br>Bivirkninger: respirasjondepresjon' },
    FIBRINOGEN: { name: 'Fibrinogen', conc: [20], unit: 'mg/ml', formula: [35000, 70000], max: [5000000], dialogText: 'Fibryga, Riastap' },
    GLYCOPYRRON: { name: 'Glykopyrron', conc: [.2], unit: 'mg/ml', formula: [5, 10], max: [400], class: 'antimuscarinic', dialogText: 'test' },
    IBUPROFEN: { name: 'Ibuprofen', conc: [6], unit: 'mg/ml', formula: [6000, 10000], max: [400000], age_limit: [6], dialogText: 'test' },
    KETAMIN: { name: 'Ketamin', conc: [10], unit: 'mg/ml', formula: [1000, 3000], class: 'sedative', dialogText: 'test' },
    KETAMIN_N: { name: 'Ketamin (nasal)*', conc: [50], unit: 'mg/ml', formula: [1000, 1500], class: 'sedative', dv: [.1], dialogText: '* Doseringsvolum for nasal administrasjon er oppgitt inkludert dødvolum på 0,1 ml' },
    KETOROLAK: { name: 'Ketorolak', conc: [30], unit: 'mg/ml', formula: [500, 600], max: [30000], age_limit: [12], dialogText: 'Toradol' },
    KLONIDIN: { name: 'Klonidin', conc: [.015], unit: 'mg/ml', formula: [1], max: [75], dialogText: 'test' },
    LIDOCAIN: { name: 'Lidokain', conc: [10], unit: 'mg/ml', formula: [3000, 7000], class: 'local', dialogText: 'test' },
    METRONIDAZOLE: { name: 'Metronidazol', unit: 'mg/ml', conc: [5], formula: [7500], max: [1500000], dialogText: 'Flagyl' },
    MIDAZOLAM: { name: 'Midazolam', conc: [1], unit: 'mg/ml', formula: [50, 100], class: 'benzo', dialogText: 'test' },
    MORFIN: { name: 'Morfin', conc: [10], unit: 'mg/ml', formula: [50, 100], max: [5000], class: 'opioid', dialogText: 'test' },
    NACL: { name: 'NaCl', conc: [1], unit: 'mmol/ml', formula: [2000], type: 'liquid', dialogText: 'test' },
    ONDANSETRON: { name: 'Ondansetron', conc: [2], unit: 'mg/ml', formula: [100], max: [4000], dialogText: 'test' },
    PARACETAMOL: { name: 'Paracetamol', conc: [10], unit: 'mg/ml', formula: [10000, 15000], dialogText: 'test' },
    PARECOXIB: { name: 'Parekoksib', conc: [10], unit: 'mg/ml', formula: [1000], max: [40000], age_limit: [12], dialogText: 'Dynastat' },
    PROPOFOL: { name: 'Propofol', conc: [10], unit: 'mg/ml', formula: [3000, 5000], class: 'sedative', dec: [0], dialogText: 'test' },
    ROCURONIUM: { name: 'Rokuronium', conc: [10], unit: 'mg/ml', formula: [600, 1200], max: [100000], class: 'nmbd', dialogText: 'test' },
    ROBINUL_NEOSTIGMIN: { name: 'Robinul/Neostigmin 0.5 /', conc: [2.5], unit: 'mg/ml', formula: [50], max: [5000], class: 'antinmbd', dialogText: 'Copneg' },
    SUGAMMADEX: { name: 'Sugammadex', conc: [100], unit: 'mg/ml', formula: [4000, 16000], max: [1200000], class: 'antinmbd', dialogText: 'test' },
    SUXAMETHONIUM: { name: 'Suksametonium', conc: [10], unit: 'mg/ml', formula: [1000, 2000], max: [100000], class: 'nmbd', dialogText: 'Curacit' },
    THIOPENTAL: { name: 'Tiopental', conc: [25], unit: 'mg/ml', formula: [5000, 8000], class: 'sedative', dialogText: 'test' },
    TRANEKSAMSYRE: { name: 'Traneksamsyre', conc: [100], unit: 'mg/ml', formula: [15000], max: [1500000], dialogText: 'Cyklokapron, Pilexam' },
    VECURONIUM: { name: 'Vekuronium', conc: [2], unit: 'mg/ml', formula: [100], max: [100000], class: 'nmbd', dialogText: 'test' },
};